version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused

linters-settings:
  govet:
    enable:
      - shadow

issues:
  exclude-rules:
    - path: _test\.go
      linters:
